services:
  postgres:
    container_name: language-school-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network
  spring-boot-app:
    container_name: spring-school
    image: spring/language-school
    ports:
      - "8088:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
volumes:
  postgres:
networks:
  spring-boot-network:
    driver: bridge