spring:
  datasource:
    # url: jdbc:postgresql://host.docker.internal:2345/school_db
    url: jdbc:postgresql://containers-us-west-193.railway.app:6249/railway
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
